### ISSUE TITLE
Sydney Caption Dataset

### ISSUE THREAD

**Issue by debjitpaul452** [201528014227051/RSICD_optimal#4]
Please provide sydney caption dataset. I cannot access the Baidu link. It's really needed for my thesis work. I can digitally sign on documents indicating it will not be used for commercial purpose. My email id: debjitpaul452@gmail.com. Thanks in advance.

**Comment by debjitpaul452** [comment]
Please provide email address of your tutor so that I can apply for dataset

**Comment by 201528014227051** [comment]
@debjitpaul452 MEGA download links are released.

**Comment by debjitpaul452** [comment]
Thank you so much.
